# NumPy Arrays

In [1]:
# Creating a simple array
my_list = [1, 2, 3]

In [2]:
# Importing the numpy library
import numpy as np

In [3]:
# Casting a simple array to a numpy array
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [6]:
# Creating a matrix out of a 2-D array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Range function (upper bound is excluded)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Range function with step size
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# Create an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
# Create a matrix of zeros
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Create an array of 1s
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
# Create a matrix of 1s
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Creating an array of equal sized intervals from a given range
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
# Creating an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Creating random numbers in the range [0, 1)
np.random.rand(5)

array([0.3919964 , 0.36855532, 0.73005838, 0.62578928, 0.52870999])

In [16]:
# Creating a matrix of random numbers
np.random.rand(5, 5)

array([[0.8369773 , 0.15970834, 0.17981307, 0.78150121, 0.97826256],
       [0.64953369, 0.03229886, 0.55525893, 0.81174504, 0.23163194],
       [0.55126587, 0.5637177 , 0.08735716, 0.90440335, 0.04417966],
       [0.53179906, 0.17961513, 0.28892041, 0.79730152, 0.88107125],
       [0.54669937, 0.91821918, 0.58162895, 0.31235618, 0.55895957]])

In [17]:
# Creating random numbers from the standard normal distribution
np.random.randn(2)

array([ 0.7737566 , -2.46764643])

In [18]:
# Creating a matrix from the standard normal distribution
np.random.randn(4, 4)

array([[-0.26402808, -0.43119637,  0.06003369,  1.09753168],
       [ 1.77514232,  1.23901723, -0.18832806, -0.77199859],
       [ 1.21531343, -1.45816237,  1.76210064,  0.52829995],
       [-0.49920589,  1.91482179, -0.55749168,  0.72247031]])

In [21]:
# Creating a random integer in a given range (upper bound is excluded)
np.random.randint(1, 100) # 100 is excluded, 1 is included

85

In [22]:
# Creating an array of random integers in a given range (upper bound is excluded)
np.random.randint(1, 100, 10)

array([78, 28, 59, 14, 74, 42, 92, 86, 60, 19])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [26]:
ranarr

array([45,  1, 20, 45,  5, 38, 21, 38, 25, 15])

In [27]:
# Method to reshape a numpy array
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
# Finding the maximum value
ranarr.max()

45

In [31]:
# Finding the minimum value
ranarr.min()

1

In [32]:
# Finding the index of maximum value
ranarr.argmax()

0

In [33]:
# Finding the index of minimum value
ranarr.argmin()

1

In [34]:
# Retrieving the shape of a numpy array 
arr.shape

(25,)

In [35]:
# Data-type of a numpy array
arr.dtype

dtype('int32')