# NumPy Indexing and Selection

In [1]:
# Import numpy
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing and Slicing

In [4]:
# Fetch element at index 8
arr[8]

8

In [5]:
# Fetch elements from index 1 to 4
arr[1:5]

array([1, 2, 3, 4])

In [6]:
# Fetch elements from index 0 to 4
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
# Fetch elements 0 to 5
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
# Fetch elements from 5 to end of array
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
# Set elements 0 to 4 as 100
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0, 11)

In [12]:
# Slicing an array
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
# Create a copy
arr_copy = arr.copy()

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

## Indexing and Selection in 2-D arrays

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[0][0]

5

In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [26]:
arr_2d[1][1]

25

In [27]:
arr_2d[2, 1]

40

In [28]:
arr_2d[1, 2]

30

In [29]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr = np.arange(1, 11)

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Conditional Selection

In [32]:
bool_arr = arr > 5

In [33]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [34]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [35]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [36]:
arr[arr < 3]

array([1, 2])

## Reshaping an array

In [37]:
arr_2d = np.arange(50).reshape(5, 10)

In [40]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])